export default {
  CHANGE_NETWORK_STATUS: 'CHANGE_NETWORK_STATUS',
  AUTH_STATE_CHANGED: 'AUTH_STATE_CHANGED',

  UPDATE_LOGIN_MESSAGE: 'UPDATE_LOGIN_MESSAGE',
  UPDATE_REGISTER_MESSAGE: 'UPDATE_REGISTER_MESSAGE',

  UPDATE_LOGGIN_IN_FLAG: 'UPDATE_LOGGIN_IN_FLAG',
  UPDATE_REGISTERING_FLAG: 'UPDATE_REGISTERING_FLAG',

  TESTING: 'TESTING'
}