export default {
  UPDATE_OVERLAY_STATE: 'UPDATE_OVERLAY_STATE',
  CHANGE_NETWORK_STATUS: 'CHANGE_NETWORK_STATUS',
  CHANGE_CURRENT_USER: 'CHANGE_CURRENT_USER',
  CHANGE_AUTH_STATE: 'CHANGE_AUTH_STATE',

  UPDATE_LOGIN_MESSAGE: 'UPDATE_LOGIN_MESSAGE',
  UPDATE_OVERLAY_MESSAGE: 'UPDATE_OVERLAY_MESSAGE',
  UPDATE_REGISTER_MESSAGE: 'UPDATE_REGISTER_MESSAGE',
  UPDATE_READ_EXTERNAL_STORAGE_PERMISSION: 'UPDATE_READ_EXTERNAL_STORAGE_PERMISSION',

  FETCH_PHOTOS: 'FETCH_PHOTOS',
  UPDATE_PHOTOS: 'UPDATE_PHOTOS',
  UPDATE_LAST_LOADED_PHOTO_CURSOR: 'UPDATE_LAST_LOADED_PHOTO_CURSOR',
  UPDATE_SELECTED_PHOTO: 'UPDATE_SELECTED_PHOTO',
  UPDATE_FETCHING_PHOTOS_FLAG: 'UPDATE_FETCHING_PHOTOS_FLAG',

  TESTING: 'TESTING',

  authStates: {
    registering: 'registering',
    loggingIn: 'loggingIn',
    loggedIn: 'loggedIn',
    loggingOut: 'loggingOut',
    loggedOut: 'loggedOut'
  },

  overlayStates: {
    loading: 'loading',
    success: 'success',
    failure: 'failure',
  }
}